version : "3.8"

services:
  envoy:
    image: envoyproxy/envoy-dev:436946bb9df0acda0e4e709592205f0d199dfb79
    restart: always
    networks:
      - main_app
    ports:
      - "80:80"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  redis:
    image: redis
    restart: always
    networks:
      - main_app
    container_name: redis-hub
    ports:
        - 6379:6379
  postgres:
    image: postgres:12-alpine
    restart: always
    networks:
      - main_app
    container_name: postgres12  
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
        - .env  
    ports: 
        - 5432:5432 
  api:
    image: 508084547447.dkr.ecr.us-east-1.amazonaws.com/hub:master
    restart: always
    networks:
      - main_app
    container_name: hub_main
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - 8080:8080
networks: 
  main_app:      
volumes:
  pgdata:    
    driver: local


