version : "3.8"

services:
  redis:
    image: redis
    container_name: redis-hub
    ports:
        - 6379:6379
  postgres:
    image: postgres:12-alpine
    container_name: postgres12  
    env_file:
        - .env  
    ports: 
        - 5432:5432 

      