http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

auth:
  accessTokenTTL: 43200m
  refreshTokenTTL: 43200m #30 days
  verificationCodeLength: 8
grpc:
 port: 7777
 servercertfile: cert/server-cert.pem
 serverkeyfile: cert/server-key.pem
 clientcacertfile: cert/ca-cert.pem
 clinetkeyfile: cert/client-key.pem
 clinetcertfile: cert/client-cert.pem